### PR TITLE
Add `yarn.lock` to `.npmignore`.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
Might wanna add `.eslintrc.js` and `.travis.yml` there, too.  Alternatively, you could use the `files` field in `package.json`.

### CODE REVIEW

**Comment by jacobp100** [comment]
Thanks for the pr! What issue does not publishing the yarn lockfile fix?

**Comment by wtgtybhertgeghgtwtg** [comment]
Not counting dependencies, the size of `css-to-react-native` is 186 KB.  114 KB of this is the `yarn.lock`.

**Comment by jacobp100** [comment]
Maybe we should go with the `files` in package.json to be consistent with styled-components.

**Comment by jacobp100** [comment]
Closing because we merged the other PR!

**Pull request closed without merging**
