### PR TITLE
Support CSS3 Variables in font family

### PR DESCRIPTION
**Pull request by birkir**
Currently failing when doing something like:

```css
font-family: var(--primary-font);
```

This PR fixes that, see the tests.

### CODE REVIEW

**Comment by birkir** [comment]
Pinging @kristerkari 😁

**Comment by birkir** [comment]
Oh yeah, sounds good. However the parser doesn't follow any CSS Spec strictly in general so I don't feel like loosly detect css variables and passing them down as-is is necesserily a bad thing.

Thanks @kristerkari, let me know if you need help!

**Comment by kristerkari** [comment]
Also, @jacobp100 mentioned that his own library has supports for CSS variables when used with React Native. I'm not sure how it's implemented as I haven't looked into it yet:
https://github.com/jacobp100/cssta#%EF%B8%8F-theming
https://github.com/jacobp100/cssta/blob/master/src/native/extractRules.js

**Comment by kristerkari** [comment]
> However the parser doesn't follow any CSS Spec strictly in general so I don't feel like loosly detect css variables and passing them down as-is is necesserily a bad thing.

True, but this is more a question of does it make sense to add support for something if it can not be fully supported. People who are just writing CSS in React Native without knowing anything about the parser might not expect something to be only partly implemented.

What I see more likely (just my opinion) that `css-to-react-native` should do:
- Not support CSS variables at all and handle the values at runtime with a separate library.
OR
- Parse values that contain CSS varibles to strings and handle the values at runtime with a separate library.

**Comment by jacobp100** [comment]
cssta pre-evaluates `var`s before putting them into `css-to-react-native`

I think adding them to this parser opens a can of worms, because one `var` can go into multiple values (e.g. `--padding: 10px 20px`)

**Comment by kristerkari** [comment]
> cssta pre-evaluates vars before putting them into css-to-react-native

That's a quite nice way to handle it. You can still get the same end result as you would without using CSS vars.

**Pull request closed without merging**
