### PR TITLE
Convert to ES6 import/export syntax

### PR DESCRIPTION
**Pull request by jacobp100**
* Converts all imports/exports to ES6
* Bundles with rollup

I question what we should do about babel though? I've kept it as-is, but RN will run babel on node_modules, so our babel config could be doing too much. Some projects will use this in node, but any maintained version of node supports classes and arrow functions. Should we ship ES6 code? @mxstbr

### CODE REVIEW

**Comment by kristerkari** [comment]
> Some projects will use this in node, but any maintained version of node supports classes and arrow functions. Should we ship ES6 code?

Looks like ES2015 is quite well supported in Node  v6+: 
http://node.green/

Node 4 is soon dead, so Node 6 is already the minimum version for most of the projects: 
https://github.com/nodejs/Release#release-schedule

**Comment by kristerkari** [comment]
I'm getting this warning when running the build

```sh
> rollup ./src/index.js -o index.js --f cjs && babel index.js -o index.js


./src/index.js → index.js...
(!) Mixing named and default exports
Consumers of your bundle will have to use bundle['default'] to access the default export, which may not be what you want. Use `exports: 'named'` to disable this warning
```

**Comment by jacobp100** [comment]
That was how Babel does it, so I was going to leave it as-is for now. Maybe we should turn Babel off after node 4 is officially out.

**Comment by kristerkari** [comment]
@jacobp100 There are again a bunch of fixes, what about releasing a new minor version?

**Comment by jacobp100** [comment]
Will do!

**Pull request merged**
