### PR TITLE
Support using "auto" when using margin shorthand

### LINKED ISSUE #77: Support "margin: 0 auto;"
Using `margin: 0 auto;` throws an error.

Here's a unit test to copy/paste:

```js
  expect(transformCss([['margin', '0 auto']])).toEqual({
    marginTop: 0,
    marginRight: 'auto',
    marginBottom: 0,
    marginLeft: 'auto',
  })
```

### PR DESCRIPTION
**Pull request by kristerkari**
Fixes #77

### CODE REVIEW

**Comment by kristerkari** [comment]
Thanks, what about releasing a new version? :)

**Comment by jacobp100** [comment]
I’ll do that tonight!

**Comment by jacobp100** [comment]
Published!

**Comment by kristerkari** [comment]
Thanks a lot :)

**Pull request merged**
